libpreopen: lib/libpreopen.c File Reference
libpreopen.c File Reference
Implementation of high-level libpreopen functions.
Functions
struct po_map * po_add (struct po_map *map, const char *path, int fd)
Add an already-opened directory to a po_map.
struct po_relpath po_find (struct po_map *map, const char *path, cap_rights_t *rights)
Find a directory whose path is a prefix of path and (on platforms that support Capsicum) that has the rights required by rights.
bool po_isprefix (const char *dir, size_t dirlen, const char *path)
int po_preopen (struct po_map *map, const char *path, int flags,...)
Pre-open a path and store it in a po_map for later use.
bool po_print_entry (const char *name, int fd, cap_rights_t rights)
Detailed Description
Implementation of high-level libpreopen functions.
The functions defined in this source file are the highest-level API calls that client code will mostly use (plus po_map_create and po_map_release). po_isprefix is also defined here because it doesn't fit anywhere else.
Definition in file libpreopen.c.
Function Documentation
po_add()
struct po_map* po_add (struct po_map * map, const char * path, int fd)
Add an already-opened directory to a po_map.
Parameters
map the map to add the path->fd mapping to
path the path that will map to this directory (which may or may not be the path used to open it)
fd the directory descriptor (must be a directory!)
Definition at line 50 of file libpreopen.c.
References po_map_assertvalid(), and po_map_enlarge().
Referenced by po_preopen().
po_find()
struct po_relpath po_find (struct po_map * map, const char * path, cap_rights_t * rights)
Find a directory whose path is a prefix of path and (on platforms that support Capsicum) that has the rights required by rights.
Parameters
map the map to look for a directory in
path the path we want to find a pre-opened prefix for
rights if non-NULL on a platform with Capsicum support, the rights any directory descriptor must have to qualify as a match
Returns
a po_relpath containing the descriptor of the best-match directory in the map (or -1 if none was found) and the remaining path, relative to the file (or undefined if no match found)
Definition at line 85 of file libpreopen.c.
References po_relpath::dirfd, po_isprefix(), po_map_assertvalid(), and po_relpath::relative_path.
po_isprefix()
bool po_isprefix (const char * dir, size_t dirlen, const char * path)
Definition at line 134 of file libpreopen.c.
Referenced by po_find().
po_preopen()
int po_preopen (struct po_map * map, const char * path, int flags, ...)
Pre-open a path and store it in a po_map for later use.
Parameters
map the map to add the path->fd mapping to
path the path to pre-open (which may be a directory if O_DIRECTORY is passed via flags)
flags flags to pass to open(2) / openat(2)
... optional file mode, as accepted by open(2)
Returns
the file descriptor of the opened directory or -1 if path is not a directory or cannot be opened or if the po_map cannot store the directory (e.g., resizing fails)
Definition at line 148 of file libpreopen.c.
References po_add(), and po_map_assertvalid().
po_print_entry()
bool po_print_entry (const char * name, int fd, cap_rights_t rights)
Definition at line 177 of file libpreopen.c.