libpreopen: include/libpreopen.h File Reference
libpreopen.h File Reference
Public header for libpreopen.
Data Structures
struct po_relpath
A filesystem path, relative to a directory descriptor.
Typedefs
typedef bool() po_map_iter_cb(const char *dirname, int dirfd, cap_rights_t)
A callback that can be used to inpect the contents of a po_map.
Functions
struct po_map * po_map_create (int capacity)
Create a po_map of at least the specified capacity.
void po_map_release (struct po_map *)
Release a reference to a po_map.
size_t po_map_foreach (const struct po_map *, po_map_iter_cb)
Iterate over a po_map, invoking a callback for each element in the map.
struct po_map * po_map_get (void)
Retrieve (and possibly create) the default map.
void po_map_set (struct po_map *)
Set the default map, taking ownership of its memory allocation(s).
struct po_map * po_add (struct po_map *map, const char *path, int fd)
Add an already-opened directory to a po_map.
int po_preopen (struct po_map *map, const char *path, int flags,...)
Pre-open a path and store it in a po_map for later use.
struct po_relpath po_find (struct po_map *map, const char *path, cap_rights_t *rights)
Find a directory whose path is a prefix of path and (on platforms that support Capsicum) that has the rights required by rights.
const char * po_last_error (void)
Retrieve a message from with the last libpreopen error.
int po_pack (struct po_map *map)
Pack a struct po_map into a shared memory segment.
struct po_map * po_unpack (int fd)
Unpack a struct po_map from a file.
Variables
po_map_iter_cb po_print_entry
A simple po_map_iter_cb that will print a po_map's entries, one per line.
Detailed Description
Public header for libpreopen.
Copyright (c) 2016 Stanley Uche Godfrey Copyright (c) 2016, 2018 Jonathan Anderson All rights reserved.
This software was developed at Memorial University under the NSERC Discovery program (RGPIN-2015-06048). Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS `‘AS IS’' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file libpreopen.h.
Typedef Documentation
po_map_iter_cb
typedef bool() po_map_iter_cb(const char *dirname, int dirfd, cap_rights_t)
A callback that can be used to inpect the contents of a po_map.
This callback can be invoked by iteration code to expose elements of a po_map (in no particular order).
Returns
whether or not to continue iterating over the po_map
Definition at line 63 of file libpreopen.h.
Function Documentation
po_add()
struct po_map* po_add (struct po_map * map, const char * path, int fd)
Add an already-opened directory to a po_map.
Parameters
map the map to add the path->fd mapping to
path the path that will map to this directory (which may or may not be the path used to open it)
fd the directory descriptor (must be a directory!)
Definition at line 50 of file libpreopen.c.
References po_map_assertvalid(), and po_map_enlarge().
Referenced by po_preopen().
po_find()
struct po_relpath po_find (struct po_map * map, const char * path, cap_rights_t * rights)
Find a directory whose path is a prefix of path and (on platforms that support Capsicum) that has the rights required by rights.
Parameters
map the map to look for a directory in
path the path we want to find a pre-opened prefix for
rights if non-NULL on a platform with Capsicum support, the rights any directory descriptor must have to qualify as a match
Returns
a po_relpath containing the descriptor of the best-match directory in the map (or -1 if none was found) and the remaining path, relative to the file (or undefined if no match found)
Definition at line 85 of file libpreopen.c.
References po_relpath::dirfd, po_isprefix(), po_map_assertvalid(), and po_relpath::relative_path.
po_last_error()
const char* po_last_error (void)
Retrieve a message from with the last libpreopen error.
Returns
NULL if there are no errors, null-terminated string otherwise
Definition at line 88 of file po_err.c.
po_map_create()
struct po_map* po_map_create (int capacity)
Create a po_map of at least the specified capacity.
The returned po_map will have a reference count of 1.
Definition at line 44 of file po_map.c.
References po_map_assertvalid().
po_map_foreach()
size_t po_map_foreach (const struct po_map * , po_map_iter_cb)
Iterate over a po_map, invoking a callback for each element in the map.
This function will cause callback to be invoked repeatedly, in no particular order, until the entire map has been iterated over or until the callback returns false.
Returns
number of elements iterated over
Definition at line 84 of file po_map.c.
References po_map_assertvalid().
po_map_get()
struct po_map* po_map_get (void)
Retrieve (and possibly create) the default map.
This can fail if there is no existing map and memory allocation fails.
Definition at line 133 of file po_libc_wrappers.c.
po_map_release()
void po_map_release (struct po_map *)
Release a reference to a po_map.
This may cause memory to be freed.
Definition at line 103 of file po_map.c.
References po_map_assertvalid().
po_map_set()
void po_map_set (struct po_map *)
Set the default map, taking ownership of its memory allocation(s).
If there is an existing default map, it will be freed before it is replaced. It is permissible to pass in a NULL map in order to clear the current default map.
Definition at line 149 of file po_libc_wrappers.c.
References po_map_assertvalid().
po_pack()
int po_pack (struct po_map * map)
Pack a struct po_map into a shared memory segment.
To inherit a po_map across the process execution boundary, it needs to be packed into an inheritable form such as a shared memory segment. This can then be unpacked in the child process for direct access.
Parameters
map the map to pack into shared memory
Returns
a file descriptor of a shared memory segment (or -1 on error)
Definition at line 88 of file po_pack.c.
References po_packed_map::count, po_packed_map::entries, po_packed_entry::fd, po_packed_entry::len, po_packed_entry::offset, po_errormessage(), po_map_assertvalid(), and po_packed_map::tablelen.
po_preopen()
int po_preopen (struct po_map * map, const char * path, int flags, ...)
Pre-open a path and store it in a po_map for later use.
Parameters
map the map to add the path->fd mapping to
path the path to pre-open (which may be a directory if O_DIRECTORY is passed via flags)
flags flags to pass to open(2) / openat(2)
... optional file mode, as accepted by open(2)
Returns
the file descriptor of the opened directory or -1 if path is not a directory or cannot be opened or if the po_map cannot store the directory (e.g., resizing fails)
Definition at line 148 of file libpreopen.c.
References po_add(), and po_map_assertvalid().
po_unpack()
struct po_map* po_unpack (int fd)
Unpack a struct po_map from a file.
Using the representation generated by po_pack, unpack a po_map and make it available for normal usage.
Parameters
fd a file containing a packed po_map representation
Definition at line 148 of file po_pack.c.
References po_packed_map::count, po_packed_map::entries, po_errormessage(), po_map_assertvalid(), and stat().
Variable Documentation
po_print_entry
po_map_iter_cb po_print_entry
A simple po_map_iter_cb that will print a po_map's entries, one per line.
Definition at line 69 of file libpreopen.h.