libpreopen: lib/po_pack.c File Reference
po_pack.c File Reference
Code for [in]packing po_map into/from dense shared memory segments.
Data Structures
struct po_packed_entry
An entry in a po_packed_map.
struct po_packed_map
Packed-in-a-buffer representation of a po_map.
Functions
int po_pack (struct po_map *map)
Pack a struct po_map into a shared memory segment.
struct po_map * po_unpack (int fd)
Unpack a struct po_map from a file.
Detailed Description
Code for [in]packing po_map into/from dense shared memory segments.
Definition in file po_pack.c.
Function Documentation
po_pack()
int po_pack (struct po_map * map)
Pack a struct po_map into a shared memory segment.
To inherit a po_map across the process execution boundary, it needs to be packed into an inheritable form such as a shared memory segment. This can then be unpacked in the child process for direct access.
Parameters
map the map to pack into shared memory
Returns
a file descriptor of a shared memory segment (or -1 on error)
Definition at line 88 of file po_pack.c.
References po_packed_map::count, po_packed_map::entries, po_packed_entry::fd, po_packed_entry::len, po_packed_entry::offset, po_errormessage(), po_map_assertvalid(), and po_packed_map::tablelen.
po_unpack()
struct po_map* po_unpack (int fd)
Unpack a struct po_map from a file.
Using the representation generated by po_pack, unpack a po_map and make it available for normal usage.
Parameters
fd a file containing a packed po_map representation
Definition at line 148 of file po_pack.c.
References po_packed_map::count, po_packed_map::entries, po_errormessage(), po_map_assertvalid(), and stat().