libpreopen: lib/po_map.c File Reference
po_map.c File Reference
Implementation of po_map management functions.
Functions
struct po_map * po_map_create (int capacity)
Create a po_map of at least the specified capacity.
struct po_map * po_map_enlarge (struct po_map *map)
size_t po_map_foreach (const struct po_map *map, po_map_iter_cb cb)
Iterate over a po_map, invoking a callback for each element in the map.
void po_map_release (struct po_map *map)
Release a reference to a po_map.
Detailed Description
Implementation of po_map management functions.
Definition in file po_map.c.
Function Documentation
po_map_create()
struct po_map* po_map_create (int capacity)
Create a po_map of at least the specified capacity.
The returned po_map will have a reference count of 1.
Definition at line 44 of file po_map.c.
References po_map_assertvalid().
po_map_enlarge()
struct po_map* po_map_enlarge (struct po_map * map)
Definition at line 69 of file po_map.c.
Referenced by po_add().
po_map_foreach()
size_t po_map_foreach (const struct po_map * , po_map_iter_cb)
Iterate over a po_map, invoking a callback for each element in the map.
This function will cause callback to be invoked repeatedly, in no particular order, until the entire map has been iterated over or until the callback returns false.
Returns
number of elements iterated over
Definition at line 84 of file po_map.c.
References po_map_assertvalid().
po_map_release()
void po_map_release (struct po_map *)
Release a reference to a po_map.
This may cause memory to be freed.
Definition at line 103 of file po_map.c.
References po_map_assertvalid().