libpreopen: lib/po_err.c File Reference
po_err.c File Reference
Error handling for libpreopen.
Functions
void po_map_assertvalid (const struct po_map *map)
void po_errormessage (const char *msg)
const char * po_last_error ()
Retrieve a message from with the last libpreopen error.
Detailed Description
Error handling for libpreopen.
Definition in file po_err.c.
Function Documentation
po_errormessage()
void po_errormessage (const char * msg)
Definition at line 80 of file po_err.c.
Referenced by po_pack(), and po_unpack().
po_last_error()
const char* po_last_error (void)
Retrieve a message from with the last libpreopen error.
Returns
NULL if there are no errors, null-terminated string otherwise
Definition at line 88 of file po_err.c.
po_map_assertvalid()
void po_map_assertvalid (const struct po_map * map)
Definition at line 61 of file po_err.c.
Referenced by po_add(), po_find(), po_map_create(), po_map_foreach(), po_map_release(), po_map_set(), po_pack(), po_preopen(), and po_unpack().